twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  welcome-message: Welcome to twitter to kafka application
  enable-mock-tweets: false
  enable-v2-twitter-client: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000

  twitter-oauth2-client-id: ${TWITTER_OAUTH2_CLIENT_ID"}
  twitter-oauth2-client-secret: ${TWITTER_OAUTH2_CLIENT_SECRET}
  twitter-oauth2-client-access-token: ${TWITTER_OAUTH2_ACCESS_TOKEN}
  twitter-oauth2-client-refresh-token: ${TWITTER_OAUTH2_REFRESH_TOKEN}
  twitter-oauth2-client-bearer-token: ${TWITTER_OAUTH2_BEARER_TOKEN}

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  max-attempts: 3
  sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: 51.103.210.207:39091, 51.103.210.207:29091, 51.103.210.207:19091
  schema-registry-url-key: schema-registry-url
  schema-registry-url: http://51.103.210.207:9092
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topic
  number-of-partitions: 3
  replication-factor: 3
